# usage:
# docker-compose -f docker/docker-compose.yml run test
version: "3.3"

services:
  common: &common
    build: .
    volumes:
      - ..:/src
    working_dir: /src

  test:
    <<: *common
    build: .
    volumes:
      - ..:/src
    working_dir: /src
    command: /bin/bash -xcl "swift test"

  shell:
    <<: *common
    entrypoint: /bin/bash