service: swift-breeze-myawewesome-webhook
awsRegion: us-east-1
swiftVersion: 6.2.0
swiftConfiguration: release
packageName: BreezeMyAwesomeWebhook
buildPath: build
cors: false
breezeWebhook:
    targetName: WebHook
    httpPath: /myawewesome-webhook