service: swift-breeze-webhook
frameworkVersion: '3'
configValidationMode: warn
useDotenv: false
provider:
  name: aws
  region: us-east-1
  disableRollback: false
  runtime: provided.al2
  httpApi:
    payload: '2.0'
    cors: false
  architecture: arm64
  versionFunctions: true
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        Resource: '*'
package:
  individually: true
functions:
  getWebHook:
    handler: get-webhook
    memorySize: 256
    description: '[${sls:stage}] get /webhook'
    package:
      artifact: build/WebHook/WebHook.zip
    events:
    - httpApi:
        path: /webhook
        method: get
  postWebHook:
    handler: post-webhook
    memorySize: 256
    description: '[${sls:stage}] post /webhook'
    package:
      artifact: build/WebHook/WebHook.zip
    events:
    - httpApi:
        path: /webhook
        method: post
